server:
  port: 8081
spring:
  profiles:
    active: dev
---
server:
  port: 8082
  servlet:
    context-path: /demo
#配置项目的访问目录
spring:
  profiles: dev

---
server:
  port: 8083
spring:
  profiles: prod